emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    output-file: "{service-name}.{version}.openapi.yaml"
    file-type: yaml
    omit-unreachable-types: true

linter:
  extends:
    - "@typespec/best-practices/recommended"
