name: Check

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

defaults:
  run:
    working-directory: "./"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup_node

      - name: lint
        run: pnpm lint

  check_test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        shard: [1/2, 2/2]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup_node

      - name: test
        env:
          TEST_SHARED: ${{ matrix.shard }}
        run: pnpm test
